# $Id: GuitarHeroSmashHits.pm,v 1.0 2009-07-05 04:29:57 codemann8 Exp $
# $Source: /var/lib/cvs/spopt/lib/Spopt/SongInfo/GuitarHeroSmashHits.pm,v $

package Spopt::SongInfo::GuitarHeroSmashHits;
use strict;

sub new                       { my $type = shift; my @args = @_; my $self = {}; bless $self, $type; $self->_init(); return $self;}
sub _prop                     { my $self = shift; if (@_ == 2) { $self->{$_[0]} = $_[1]; } return $self->{$_[0]}; }
sub get_songarr               { my $self = shift; my @out = @{$self->{songarr}}; return @out; }
sub get_songarr_for_game      { my ($self,$game) = @_; my @out = grep { $_->{'game'} eq $game } @{$self->{songarr}}; return @out; } 
sub get_tier_titles_for_game  { my ($self,$game) = @_; my @out = @{$self->{'tier_titles'}{$game}}; return @out; }

sub _init {
    my $self = shift;

    @{$self->{'tier_titles'}{'ghsh'}} = (
        'Amazon Rain Forest',
        'Grand Canyon',
        'Polar Ice Cap',
        'London Sewerage System',
        'The Sphinx',
        'The Great Wall Of China',
        'The Lost City of Atlantis',
        'Quebec City',
    );

    @{$self->{'songarr'}} = (
        {
        game   => 'ghsh',
        tier   => 3,
        name   => q{Back In The Saddle},
        artist => q{Aerosmith},
        year   => 1977,
        file   => 'backinthesaddle.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 5,
        name   => q{Bark At The Moon},
        artist => q{Ozzy Osbourne},
        year   => 1983,
        file   => 'barkatthemoon.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 4,
        name   => q{Barracuda},
        artist => q{Heart},
        year   => 1977,
        file   => 'barracuda.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 6,
        name   => q{Beast And The Harlot},
        artist => q{Avenged Sevenfold},
        year   => 2005,
        file   => 'beastandtheharlot.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 3,
        name   => q{Carry On Wayward Son},
        artist => q{Kansas},
        year   => 1976,
        file   => 'carryonmywaywardson.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 6,
        name   => q{Caught In A Mosh},
        artist => q{Anthrax},
        year   => 1987,
        file   => 'caughtinamosh.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 2,
        name   => q{Cherry Pie},
        artist => q{Warrant},
        year   => 1990,
        file   => 'cherrypie.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 5,
        name   => q{Cowboys From Hell (Live)},
        artist => q{Pantera},
        year   => 1991,
        file   => 'cowboysfromhell.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 5,
        name   => q{Cult Of Personality},
        artist => q{Living Colour},
        year   => 2007,
        file   => 'cultofpersonality.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 4,
        name   => q{Electric Eye},
        artist => q{Judas Priest},
        year   => 1982,
        file   => 'electriceye.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 5,
        name   => q{Free Bird},
        artist => q{Lynyrd Skynyrd},
        year   => 1973,
        file   => 'freebird.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 4,
        name   => q{Freya},
        artist => q{The Sword},
        year   => 2006,
        file   => 'freya.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 1,
        name   => q{Godzilla},
        artist => q{Blue Öyster Cult},
        year   => 1977,
        file   => 'godzilla.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 0,
        name   => q{Heart Shaped Box},
        artist => q{Nirvana},
        year   => 1993,
        file   => 'heartshapedbox.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 2,
        name   => q{Hey You},
        artist => q{The Exies},
        year   => 2004,
        file   => 'heyyou.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 0,
        name   => q{Hit Me With Your Best Shot},
        artist => q{Pat Benatar},
        year   => 1980,
        file   => 'hitmewithyourbestshot.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 0,
        name   => q{I Love Rock 'N Roll},
        artist => q{Joan Jett and The Blackhearts},
        year   => 1982,
        file   => 'iloverockandroll.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 2,
        name   => q{I Wanna Rock},
        artist => q{Twisted Sister},
        year   => 1984,
        file   => 'iwannarock.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 3,
        name   => q{Killer Queen},
        artist => q{Queen},
        year   => 1974,
        file   => 'killerqueen.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 1,
        name   => q{Killing In The Name},
        artist => q{Rage Against The Machine},
        year   => 1992,
        file   => 'killinginthenameof.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 5,
        name   => q{Laid To Rest},
        artist => q{Lamb of God},
        year   => 2004,
        file   => 'laidtorest.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 1,
        name   => q{Lay Down},
        artist => q{Priestess},
        year   => 2006,
        file   => 'laydown.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 3,
        name   => q{Message In A Bottle},
        artist => q{The Police},
        year   => 1979,
        file   => 'messageinabottle.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 2,
        name   => q{Miss Murder},
        artist => q{AFI},
        year   => 2006,
        file   => 'missmurder.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 3,
        name   => q{Monkey Wrench},
        artist => q{Foo Fighters},
        year   => 1997,
        file   => 'monkeywrench.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 1,
        name   => q{More Than A Feeling},
        artist => q{Boston},
        year   => 1976,
        file   => 'morethanafeeling.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 1,
        name   => q{Mother},
        artist => q{Danzig},
        year   => 1988,
        file   => 'mother.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 4,
        name   => q{No One Knows},
        artist => q{Queens of The Stone Age},
        year   => 2002,
        file   => 'nooneknows.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 2,
        name   => q{Nothin' But A Good Time},
        artist => q{Poison},
        year   => 1988,
        file   => 'nothinbutagoodtime.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 6,
        name   => q{Play With Me},
        artist => q{Extreme},
        year   => 1989,
        file   => 'playwithme.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 5,
        name   => q{Psychobilly Freakout},
        artist => q{Reverend Horton Heat},
        year   => 1990,
        file   => 'psychobillyfreakout.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 6,
        name   => q{Raining Blood},
        artist => q{Slayer},
        year   => 1986,
        file   => 'rainingblood.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 0,
        name   => q{Rock And Roll All Nite},
        artist => q{Kiss},
        year   => 1975,
        file   => 'rockandrollallnite.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 3,
        name   => q{Round And Round},
        artist => q{Ratt},
        year   => 1984,
        file   => 'roundandround.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 2,
        name   => q{Shout At The Devil},
        artist => q{Mötley Crüe},
        year   => 1983,
        file   => 'shoutatthedevil.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 3,
        name   => q{Smoke On The Water},
        artist => q{Deep Purple},
        year   => 1972,
        file   => 'smokeonthewater.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 0,
        name   => q{Stellar},
        artist => q{Incubus},
        year   => 1999,
        file   => 'stellar.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 4,
        name   => q{Stop!},
        artist => q{Jane's Addiction},
        year   => 1990,
        file   => 'stop.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 1,
        name   => q{Take It Off},
        artist => q{The Donnas},
        year   => 2002,
        file   => 'takeitoff.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 0,
        name   => q{Take Me Out},
        artist => q{Franz Ferdinand},
        year   => 2004,
        file   => 'takemeout.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 1,
        name   => q{Them Bones},
        artist => q{Alice In Chains},
        year   => 1992,
        file   => 'thembones.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 7,
        name   => q{Through The Fire And Flames},
        artist => q{DragonForce},
        year   => 2006,
        file   => 'throughthefire.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 4,
        name   => q{Thunder Kiss '65},
        artist => q{White Zombie},
        year   => 1992,
        file   => 'thunderkiss65.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 4,
        name   => q{Trippin' On A Hole In A Paper Heart},
        artist => q{Stone Temple Pilots},
        year   => 1996,
        file   => 'trippinonahole.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 6,
        name   => q{The Trooper},
        artist => q{Iron Maiden},
        year   => 1983,
        file   => 'thetrooper.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 2,
        name   => q{Unsung (Live In Chicago)},
        artist => q{Helmet},
        year   => 1992,
        file   => 'unsung.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 1,
        name   => q{Woman},
        artist => q{Wolfmother},
        year   => 2006,
        file   => 'woman.mid.qb',
        },
		{
        game   => 'ghsh',
        tier   => 5,
        name   => q{YYZ},
        artist => q{Rush},
        year   => 1981,
        file   => 'yyz.mid.qb',
        },
    );
}

1;
